---
substitutions:
  name: "esp8566-12f-template"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://zipkid/esp-templates/esp8566-12f-template.yaml

wifi:
  networks: []
    # - ssid: !secret wifi_ssid
    #   password: !secret wifi_password

  # Set up a wifi access point
  ap:
    password: "esp8566-12f"

captive_portal:
